# Generated by Django 4.2.16 on 2024-12-03 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="プロジェクトID"
                    ),
                ),
                (
                    "logical_project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="論理プロジェクトID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="全角100文字以内",
                        max_length=100,
                        verbose_name="プロジェクト名",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="全角1000文字以内",
                        verbose_name="プロジェクトの説明",
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終更新日時"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spaces.space",
                        verbose_name="スペースID",
                    ),
                ),
            ],
        ),
    ]
