# Generated by Django 4.2.16 on 2024-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="secret_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
