# Generated by Django 4.2.16 on 2024-12-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0002_remove_spaceaccount_account_and_more"),
        ("accounts", "0002_account_secret_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
