version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Fetching database credentials from Secrets Manager..."
      - DB_SECRET=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --query 'SecretString' --output text)
      - export DATABASE_HOST=$(echo $DB_SECRET | jq -r '.DB_HOST')
      - export DATABASE_PORT=$(echo $DB_SECRET | jq -r '.DB_PORT')
      - export DATABASE_NAME=$(echo $DB_SECRET | jq -r '.DB_NAME')
      - export DATABASE_USER=$(echo $DB_SECRET | jq -r '.DB_USERNAME')
      - export DATABASE_PASSWORD=$(echo $DB_SECRET | jq -r '.DB_PASSWORD')
      - export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

  build:
    commands:
      - echo "Running Django migrations..."
      - python manage.py migrate
      - echo "Database migration completed on `date`"

artifacts:
  files:
    - migration_logs/*
  discard-paths: yes
