# Generated by Django 4.2.16 on 2024-12-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
