# Generated by Django 4.2.16 on 2024-12-06 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField()),
                ("secret_key", models.CharField(blank=True, max_length=32, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="お知らせID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("content", models.TextField(max_length=1000, verbose_name="内容")),
                (
                    "announcements_from_at",
                    models.DateTimeField(verbose_name="お知らせ開始日時"),
                ),
                (
                    "announcements_to_at",
                    models.DateTimeField(verbose_name="お知らせ終了日時"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ファイルパス"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="権限ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="権限名")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="スペースID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="スペース名")),
                (
                    "icon_image_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="アイコン画像フルパス"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="スペースの説明"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
            ],
            options={
                "db_table": "spaces",
            },
        ),
        migrations.CreateModel(
            name="SpaceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="スペースアカウントID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.account",
                        verbose_name="アカウントID",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.space",
                        verbose_name="スペースID",
                    ),
                ),
            ],
            options={
                "db_table": "space_accounts",
            },
        ),
        migrations.CreateModel(
            name="SpaceAccountPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="スペースアカウント権限ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.permission",
                        verbose_name="権限ID",
                    ),
                ),
                (
                    "space_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.spaceaccount",
                        verbose_name="スペースアカウントID",
                    ),
                ),
            ],
            options={
                "db_table": "space_accounts_permissions",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="プロジェクトID"
                    ),
                ),
                (
                    "logical_project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="論理プロジェクトID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="全角100文字以内",
                        max_length=100,
                        verbose_name="プロジェクト名",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="全角1000文字以内",
                        verbose_name="プロジェクトの説明",
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終更新日時"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.space",
                        verbose_name="スペースID",
                    ),
                ),
            ],
        ),
    ]
