# Generated by Django 4.2.16 on 2024-12-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="reset_token",
            field=models.CharField(
                blank=True,
                help_text="パスワードリセット用のトークン",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="token_expiration",
            field=models.DateTimeField(
                blank=True, help_text="トークンの有効期限", null=True
            ),
        ),
    ]
