# Generated by Django 4.2.16 on 2024-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_account_reset_token_account_token_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_2fa_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
