# Generated by Django 4.2.16 on 2024-12-06 08:53

from django.db import migrations, models
import django.db.models.deletion
import user_app.contents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="コンテンツID"
                    ),
                ),
                (
                    "logical_contents_id",
                    models.CharField(
                        default=user_app.contents.models.Contents.generate_random_id,
                        max_length=6,
                        unique=True,
                        verbose_name="論理コンテンツID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="コンテンツ名")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="コンテンツの説明"),
                ),
                (
                    "production_status_id",
                    models.IntegerField(
                        choices=[(1, "UNDER_CONSTRUCTION"), (2, "COMPLETION")],
                        default=1,
                        verbose_name="製作ステータスID",
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終更新日時"
                    ),
                ),
                (
                    "script_path",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        verbose_name="スクリプトファイルパス",
                    ),
                ),
                (
                    "is_10_return_move_on_display",
                    models.BooleanField(default=False, verbose_name="10秒戻る/進む"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.project",
                        verbose_name="プロジェクトID",
                    ),
                ),
            ],
            options={
                "verbose_name": "コンテンツ",
                "verbose_name_plural": "コンテンツ",
            },
        ),
    ]
