# Generated by Django 4.2.16 on 2024-12-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="お知らせID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "announcements_from_at",
                    models.DateTimeField(verbose_name="お知らせ開始日時"),
                ),
                (
                    "announcements_to_at",
                    models.DateTimeField(verbose_name="お知らせ終了日時"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ファイルパス"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
            ],
        ),
    ]
