name: Feature Branch CI

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "feature/*"

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: npi
          POSTGRES_PASSWORD: password
          POSTGRES_DB: npi_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U npi"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: "npi.settings.github_actions"

      - name: Run tests
        run: python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: "npi.settings.github_actions"

      - name: Run code formatting check (Black)
        run: black . --check

      - name: Run linting (Flake8)
        run: flake8 .
        env:
          FLAKE8_MAX_LINE_LENGTH: 170
          FLAKE8_MAX_COMPLEXITY: 15
          FLAKE8_IGNORE: F403,F405
